name: pajakin_aja
<<<<<<< HEAD
description: Aplikasi kalkulator pajak lengkap (PPh, UMKM, PBB, PPN)
=======
description: A new Flutter project.
>>>>>>> 6c1cc143556c4c7dadd7d75c38a5dbdaf6d09701
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
<<<<<<< HEAD

  assets:
    - assets/logo.png
=======
  assets:
    - assets/images/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
>>>>>>> 6c1cc143556c4c7dadd7d75c38a5dbdaf6d09701
