name: pajakin_fix
description: Aplikasi kalkulator pajak lengkap (PPh, UMKM, PBB, PPN)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
=======
  shared_preferences: ^2.2.2
  intl: ^0.19.0
>>>>>>> 1430f5cddce99cb320d408ffac2c47989ea3b856

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
